/**
 * 状态管理
 */

// 导航栏
export const ELMENU_SWITCH = 'ELMENU_SWITCH'
export const HEADERNAV_SWITCH = 'HEADERNAV_SWITCH'

// 登录
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_OUT_LOGIN = 'USER_OUT_LOGIN'

// 公共部分
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
export const GET_BOXLIST_SUCCESS = 'GET_BOXLIST_SUCCESS'
export const GET_PROVINCELIST_SUCCESS = 'GET_PROVINCELIST_SUCCESS'
export const GET_CITYLIST_SUCCESS = 'GET_CITYLIST_SUCCESS'
export const GET_AREALIST_SUCCESS = 'GET_AREALIST_SUCCESS'
export const GET_COMMUNITYLIST_SUCCESS = 'GET_COMMUNITYLIST_SUCCESS'
export const RESET_UNITLIST_SUCCESS = 'RESET_UNITLIST_SUCCESS'
export const GET_PRODUCTBIGCLASSLIST_SUCCESS = 'GET_PRODUCTBIGCLASSLIST_SUCCESS'
export const GET_PRODUCTMEDIUMCLASSLIST_SUCCESS = 'GET_PRODUCTMEDIUMCLASSLIST_SUCCESS'
export const GET_PRODUCTSMALLCLASSLIST_SUCCESS = 'GET_PRODUCTSMALLCLASSLIST_SUCCESS'
export const GET_DICTIONARYSEARCHLIST_SUCCESS = 'GET_DICTIONARYSEARCHLIST_SUCCESS'
export const RESET_CLASS_SUCCESS = 'RESET_CLASS_SUCCESS'
export const GET_PRODUCTSUPPLIER_SUCCESS = 'GET_PRODUCTSUPPLIER_SUCCESS'

// 地图概览
export const GET_OVERVIEW_DATA_SUCCESS = 'GET_OVERVIEW_DATA_SUCCESS'

// 销售管理
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS'
export const GET_ORDERLIST_SUCCESS = 'GET_ORDERLIST_SUCCESS'
export const GET_PRODUCTSALESDATA_SUCCESS = 'GET_PRODUCTSALESDATA_SUCCESS'

// 盒子管理
export const GET_PROVINCEADMINLIST_SUCCESS = 'GET_PROVINCEADMINLIST_SUCCESS'
export const GET_CITYADMINLIST_SUCCESS = 'GET_CITYADMINLIST_SUCCESS'
export const GET_AREAADMINLIST_SUCCESS = 'GET_AREAADMINLIST_SUCCESS'
export const GET_COMMUNITYADMINLIST_SUCCESS = 'GET_COMMUNITYADMINLIST_SUCCESS'


// 用户管理
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS'
export const GET_USERBASIS_DATA_SUCCESS = 'GET_USERBASIS_DATA_SUCCESS'
export const GET_USERBUYRECORD_SUCCESS = 'GET_USERBUYRECORD_SUCCESS'

// 员工管理
export const GET_STAFFTALIST_SUCCESS = 'GET_STAFFTALIST_SUCCESS'

// 资料管理
export const GET_BIGCLASS_SUCCESS = 'GET_BIGCLASS_SUCCESS'
export const GET_MEDIUMCLASS_SUCCESS = 'GET_MEDIUMCLASS_SUCCESS'
export const GET_SMALLCLASS_SUCCESS = 'GET_SMALLCLASS_SUCCESS'
export const GET_NBIGCLASS_SUCCESS = 'GET_NBIGCLASS_SUCCESS'
export const GET_NMEDIUMCLASS_SUCCESS = 'GET_NMEDIUMCLASS_SUCCESS'
export const GET_SUPPLIERLIST_SUCCESS = 'GET_SUPPLIERLIST_SUCCESS'
export const GET_SUPPLIERINFO_SUCCESS = 'GET_SUPPLIERINFO_SUCCESS'
export const GET_DICTIONARYTYPELIST_SUCCESS = 'GET_DICTIONARYTYPELIST_SUCCESS'
export const GET_DICTIONARYLIST_SUCCESS = 'GET_DICTIONARYLIST_SUCCESS'
export const GET_PRODUCTLIST_SUCCESS = 'GET_PRODUCTLIST_SUCCESS'
